<?php

/**
 * Implements hook_menu().
 */
function startOfWeek($aDate){
    $d=strtotime($aDate);
    return strtotime(date('Y-m-d',$d).' - '.date("w",$d).' days');
}
function afisha_ajax_menu()
{
    $items['node/get/ajax/%/%'] = array(
        'page callback' => 'afisha_ajax_ajax_get_ajax', // Render HTML.
        'page arguments' => array(3, 4, 5),
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
        'delivery callback' => 'afisha_ajax_ajax_callback',  // Magic goes here.
    );
    return $items;
}

/**
 * @param $tid
 * @param $date1
 * @param null $date2
 * @return mixed
 */
function afisha_ajax_ajax_get_ajax($tid, $date1, $date2 = null)
{

    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'afisha')
        ->propertyCondition('status', NODE_PUBLISHED);

    if (is_numeric($date1)) {

        if ($date1 && $date2 == "") {

            $query->fieldCondition('field_date_afisha', 'value', $date1, '=');

        } else {
            $query->fieldCondition('field_date_afisha', 'value', $date1, '>=');

            $query->fieldCondition('field_date_afisha', 'value', $date2, '<=');
        }

    }

    if ($tid != 'all') {
        $query->fieldCondition('field_cat_afisha', 'tid', $tid, '=');
    }


    $query->range(0, 150);
    $result = $query->execute();
    if (isset($result['node'])) {
        $news_items_nids = array_keys($result['node']);
        $news_items = entity_load('node', $news_items_nids);
    }
    /// for duration
    $query2 = new EntityFieldQuery();
    $query2->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'afisha')
        ->propertyCondition('status', NODE_PUBLISHED);

    if (is_numeric($date1)) {

        $query2->fieldCondition('field_field_duration_date_afisha', 'value', $date1, '<=');

        $query2->fieldCondition('field_field_duration_date_afisha', 'value', $date2, '>=');


    }

    if ($tid != 'all') {
        $query2->fieldCondition('field_cat_afisha', 'tid', $tid, '=');
    }


    $query2->range(0, 150);
    $result2 = $query2->execute();
    if (isset($result2['node'])) {
        $news_items_nids2 = array_keys($result2['node']);
        $news_items2 = entity_load('node', $news_items_nids2);
    }


    // var_dump($news_items);exit;

    return [$news_items, $news_items2, $date1, $date2];
    /*var_dump($date1[0]);
    var_dump($news_items);
    exit; */
    /*
    $node = node_load($nid);
    return node_view($node, 'teaser');
    */
}

function afisha_ajax_ajax_callback($page_callback_result)
{


    summary($page_callback_result[0], $page_callback_result[2], $page_callback_result[3]);
    summary($page_callback_result[1], $page_callback_result[2], $page_callback_result[3]);

    drupal_page_footer();
}

function summary($page_callback_result, $apidate, $apidate2)
{
    $arr = [
        'января',
        'февраля',
        'марта',
        'апреля',
        'мая',
        'июня',
        'июля',
        'августа',
        'сентября',
        'октября',
        'ноября',
        'декабря'
    ];

    $output = "";
    $year = date('Y');
    foreach ($page_callback_result as $node) {
        $my_image_url ='';

        // $my_image_url = file_create_url($node->field_image_afisha['und'][0]['uri']);
        $my_image_url = image_style_url("afisha", $node->field_image_afisha['und'][0]['uri']);


        $month = date('m', $node->field_date_afisha['und'][0]['value']) - 1;
        $path = 'node/' . $node->nid;
        //$path =  $node->nid ;
        $alias = drupal_get_path_alias($path);

        $term = taxonomy_term_load($node->field_cat_afisha['und'][0]['tid']);
        $terms = taxonomy_get_term_by_name($term->name);
        foreach ($terms as $value) {
            $value = $value->field_alias_afisha;


        }
        $day = gmdate("d", $apidate);
        $day2 = (int)gmdate("d", $apidate2) - 1;
        $monthsearch = (int)gmdate("m", $apidate) - 1;
        $monthsearch2 = (int)gmdate("m", $apidate2) - 1;


        $count = count($node->field_date_afisha['und']);
        if ($count > 1) {  /// if many dates

            $redydate = $day . ' ' . $arr[$monthsearch];

        } else {

            $redydate = date('d', $node->field_date_afisha['und'][0]['value']) . ' ' . $arr[$month];

        }

        if ($node->field_field_duration_date_afisha['und'][0]['value']) {

            /*$custom_date = strtotime( date('d-m-Y', strtotime($day2.'-'.intVal($monthsearch2+1).'-'.$year)) );
            $week_start_day = date('d', strtotime('this week last monday', $custom_date));
            $week_start_mounth = date('m', strtotime('this week last monday', $custom_date));*/
            $mnt_d = date('d', startOfWeek($year . "-" . intVal($monthsearch2 + 1) . "-" . $day2));
            $mnt_m = date('m', startOfWeek($year . "-" . intVal($monthsearch2 + 1) . "-" . $day2));
            // !=$day2 &&  $mnt_m != intVal($monthsearch2+1)
            if(intVal($mnt_d + 1) !=$day2){
            $output .= '   
                     <li  class="culture-detail-item  ' . $value['und'][0]['value'] . '">
                         <a href="' . $alias . '">
                         
                            <div class="culture-top-block clearfix">
                                <span>' . $term->name . '</span>
                            </div> 
                                  <div class="afisha-row-image">   
                                      <div class="afisha-date">' . $day . ' ' . $arr[$monthsearch] . '</div> 
                                      <img src="' . $my_image_url . '" alt="' . $node->title . '" />
                                          <div class="afisha-bottom-block-row">
                                          <div class="afisha-bottom-block">
                                              <h3>' . $node->title . '</h3> 
                                                    </div>
                                          </div>
                                  </div>
        
                         </a>         
                     </li>';
        }
        } else {
            foreach ($node->field_date_afisha['und'] as $date) {     // for array dates

                $dayvalue = (int)gmdate("d", $date['value']);

                $monthvalue = (int)gmdate("m", $date['value']) - 1;

                // var_dump($node->field_field_duration_date_afisha['und']);
//
                if ($day == $dayvalue && $monthsearch == $monthvalue) {   // check if entry date

                    $accept = true;

                } else if ($day2 == $dayvalue && $monthsearch2 == $monthvalue) {
                    $accept = true;
                } else {
                    $accept = false;
                }


                if ($accept) {

                    //  if($day ==  $dayvalue   ){

                    $output .= '   
                     <li class="culture-detail-item  ' . $value['und'][0]['value'] . '">
                         <a href="' . $alias . '">
                         
                            <div class="culture-top-block clearfix">
                                <span>' . $term->name . '</span>
                            </div> 
                                  <div class="afisha-row-image">   
                                      <div class="afisha-date">' . $redydate . '</div> 
                                      <img src="' . $my_image_url . '" alt="' . $node->title . '" />
                                          <div class="afisha-bottom-block-row">
                                          <div class="afisha-bottom-block">
                                              <h3>' . $node->title . '</h3> 
                                                    </div>
                                          </div>
                                  </div>
        
                         </a>         
                     </li>';
                }


            }
        }

    }

    print $output;


}