<?php

/**
 * Implements hook_menu().
 */
function article_ajax_menu() {
    $items['article/get/ajax/%'] = array(
        'page callback' => 'article_ajax_ajax_get_ajax', // Render HTML.
        'page arguments' => array(3),
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
        'delivery callback' => 'article_ajax_ajax_callback',  // Magic goes here.
    );
    return $items;
}

/**
 * @param $tid
 * @param $date1
 * @param null $date2
 * @return mixed
 */
function article_ajax_ajax_get_ajax($pager) {
    $value = intval(12*$pager);
    $query  = new EntityFieldQuery();
    $query  ->entityCondition('entity_type', 'node')
            ->entityCondition('bundle', 'article')
            ->propertyCondition('status', NODE_PUBLISHED)
            ->propertyOrderBy('created', 'DESC')
            ->range($value, 12);

    $result = $query->execute();
    if (isset($result['node'])) {
        $news_items_nids = array_keys($result['node']);
        $news_items = entity_load('node', $news_items_nids);
    }

    return $news_items;

}

function article_ajax_ajax_callback($page_callback_result) {

    $arr = [
        'января',
        'февраля',
        'марта',
        'апреля',
        'мая',
        'июня',
        'июля',
        'августа',
        'сентября',
        'октября',
        'ноября',
        'декабря'
    ];



    $output = "";

    foreach ($page_callback_result as $node) {
      /*  echo '<pre>';
        print_r($node);
        echo '</pre>';*/
        $day = (int)  gmdate("d", $node->created);
        $monthsearch = (int)  gmdate("m",  $node->created)-1;


        $my_image_url = file_create_url($node->field_image['und'][0]['uri']);
        $output .= '
                <li class="item-news-page">
                    <div class="news-item">
                    <div class="date-news">' . $day . ' ' . $arr[$monthsearch] . '</div>
                    <img src="'.$my_image_url.'"  />
                    <h3><a href="'.drupal_get_path_alias('node/' . $node->nid).'"> ' . $node->title . '</a></h3>
                    <div  class="news-text-block">
                        ' . $node->field_anons['und'][0]['value'] . '
                    </div>
                    </div>
                </li>
                ';


    }
    print $output;

    drupal_page_footer();
}